Fix issue parsing empty string
On the version of `oj` we're using in the services, we'll get a parse
error when sending an empty string to `Oj.load`, and we've been seeing
this in pre-prod since v0.5.1 as previously we were getting the cache
key name wrong by duplicating namespace.

We now check for an empty string, and return that back without
deserializing.

Some additional info about oj handling empty string.

```
pry(main)> Oj::VERSION
=> "3.2.0"
pry(main)> Oj.load("")
EncodingError: An empty string is not a valid JSON string.
```

version being used in `cache_store_redis` tests
```
pry(#<RedisCacheStore>)> Oj.load('')
=> nil
pry(#<RedisCacheStore>)> Oj.load("\"\"")
=> ""
pry(#<RedisCacheStore>)> Oj.load("\" \"")
=> " "
pry(#<RedisCacheStore>)> Oj::VERSION
=> "2.15.0"
```

latest version
```
pry(main)> Oj.load("")
=> nil
pry(main)> Oj::VERSION
=> "3.3.10"```
```

https://github.com/ohler55/oj/issues/435